version: '3.8'

services:
  # Django application
  web:
    build: .
    command: ["daphne", "django_chat.asgi:application", "--bind", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=django_chat.settings

  # Redis for channel layer and Celery
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Celery worker
  celery:
    build: .
    command: ["celery", "-A", "django_chat", "worker", "--loglevel=info", "--concurrency=4"]
    depends_on:
      - redis
    volumes:
      - .:/app

