# Generated by Django 5.2 on 2025-04-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Organization',
            new_name='organization',
        ),
    ]
